// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class AspNetUser : IAggregateRoot
{
    public int Id { get; set; }

    public int? AccessFailedCount { get; set; }

    public string ConcurrencyStamp { get; set; }

    public string Email { get; set; }

    public bool? EmailConfirmed { get; set; }

    public bool? LockoutEnabled { get; set; }

    public DateTime? LockoutEnd { get; set; }

    public string NormalizedEmail { get; set; }

    public string NormalizedUserName { get; set; }

    public string PasswordHash { get; set; }

    public string PhoneNumber { get; set; }

    public bool? PhoneNumberConfirmed { get; set; }

    public string SecurityStamp { get; set; }

    public bool? TwoFactorEnabled { get; set; }

    public string UserName { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsActive { get; set; }

    public string StripeVendorId { get; set; }

    public string StripeDashboardAccess { get; set; }

    public string StripeVendorStatus { get; set; }

    public string ProfileImage { get; set; }

    public string Bio { get; set; }

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; } = new List<AspNetUserClaim>();

    public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; } = new List<AspNetUserLogin>();

    public virtual ICollection<AspNetUserRole> AspNetUserRoles { get; set; } = new List<AspNetUserRole>();

    public virtual ICollection<AspNetUserToken> AspNetUserTokens { get; set; } = new List<AspNetUserToken>();

    public virtual ICollection<Attribute> Attributes { get; set; } = new List<Attribute>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Profile> Profiles { get; set; } = new List<Profile>();

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    public virtual ICollection<UserWishlist> UserWishlists { get; set; } = new List<UserWishlist>();

    public virtual ICollection<VendorOrderRelation> VendorOrderRelations { get; set; } = new List<VendorOrderRelation>();
}