// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Attribute : IAggregateRoot
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? UserId { get; set; }

    public string Language { get; set; }

    public string Slug { get; set; }

    public int? ShopId { get; set; }

    public virtual Shop Shop { get; set; }

    public virtual AspNetUser User { get; set; }

    public virtual ICollection<Value> Values { get; set; } = new List<Value>();
}