// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Author : IAggregateRoot
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Bio { get; set; }

    public string Quote { get; set; }

    public int? ProductsCount { get; set; }

    public string Born { get; set; }

    public string Death { get; set; }

    public string Languages { get; set; }

    public int? ImageId { get; set; }

    public int? CoverImageId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? ShopId { get; set; }

    public bool? IsApproved { get; set; }

    public string Slug { get; set; }

    public virtual Image Image { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual Shop Shop { get; set; }
}