// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Balance : IAggregateRoot
{
    public int Id { get; set; }

    public int AdminCommissionRate { get; set; }

    public string Shop { get; set; }

    public int? ShopId { get; set; }

    public decimal? TotalEarnings { get; set; }

    public decimal? WithDrawnAmount { get; set; }

    public decimal? CurrentBalance { get; set; }

    public string AccountNumber { get; set; }

    public string AccountHolderName { get; set; }

    public string AccountHolderEmail { get; set; }

    public string BankName { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Shop ShopNavigation { get; set; }
}