// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Banner : IAggregateRoot
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int? TypeId { get; set; }

    public string Description { get; set; }

    public int? ImageId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? ProductId { get; set; }

    public virtual Image Image { get; set; }

    public virtual ICollection<Manufacture> Manufactures { get; set; } = new List<Manufacture>();

    public virtual Product Product { get; set; }

    public virtual Type Type { get; set; }
}