// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class CategoryTranslation : IAggregateRoot
{
    public int Id { get; set; }

    public int? CategoryId { get; set; }

    public string Language { get; set; }

    public virtual Category Category { get; set; }
}