// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Category : IAggregateRoot
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Slug { get; set; }

    public string Language { get; set; }

    public string Icon { get; set; }

    public int? ParentId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? TypeId { get; set; }

    public int? ImageId { get; set; }

    public string Size { get; set; }

    public virtual ICollection<CategoryTranslation> CategoryTranslations { get; set; } = new List<CategoryTranslation>();

    public virtual ICollection<Engine> Engines { get; set; } = new List<Engine>();

    public virtual Image Image { get; set; }

    public virtual ICollection<Category> InverseParent { get; set; } = new List<Category>();

    public virtual Category Parent { get; set; }

    public virtual ICollection<Product> ProductsNavigation { get; set; } = new List<Product>();

    public virtual ICollection<SubCategoryList> SubCategoryLists { get; set; } = new List<SubCategoryList>();

    public virtual Type Type { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}