// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Engine : IAggregateRoot
{
    public int Id { get; set; }

    public int? Year { get; set; }

    public int? CategoryId { get; set; }

    public int? SubcategoryId { get; set; }

    public int? ManufacturerId { get; set; }

    public int? ModelId { get; set; }

    public string Engine1 { get; set; }

    public string HollanderCode { get; set; }

    public virtual Category Category { get; set; }

    public virtual Manufacture Manufacturer { get; set; }

    public virtual ManufacturerModel Model { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual SubCategoryList Subcategory { get; set; }
}