// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class FlashSaleImage : IAggregateRoot
{
    public int Id { get; set; }

    public string Images { get; set; }
}