// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Gallery : IAggregateRoot
{
    public int Id { get; set; }

    public int? ProductId { get; set; }

    public string OriginalUrl { get; set; }

    public string ThumbnailUrl { get; set; }

    public virtual Product Product { get; set; }
}