// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Image : IAggregateRoot
{
    public int Id { get; set; }

    public string OriginalUrl { get; set; }

    public string ThumbnailUrl { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Author> Authors { get; set; } = new List<Author>();

    public virtual ICollection<Banner> Banners { get; set; } = new List<Banner>();

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

    public virtual ICollection<Manufacture> Manufactures { get; set; } = new List<Manufacture>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<Profile> Profiles { get; set; } = new List<Profile>();

    public virtual ICollection<Shop> ShopCoverImages { get; set; } = new List<Shop>();

    public virtual ICollection<Shop> ShopLogoImages { get; set; } = new List<Shop>();

    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
}