// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Manufacture : IAggregateRoot
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Slug { get; set; }

    public string Language { get; set; }

    public string TranslatedLanguages { get; set; }

    public int? ProductsCount { get; set; }

    public bool? IsApproved { get; set; }

    public int? SocialId { get; set; }

    public int? TypeId { get; set; }

    public int? ImageId { get; set; }

    public string Description { get; set; }

    public string Website { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? BannerId { get; set; }

    public int? PromotionalSliderId { get; set; }

    public virtual Banner Banner { get; set; }

    public virtual ICollection<Engine> Engines { get; set; } = new List<Engine>();

    public virtual Image Image { get; set; }

    public virtual ICollection<ManufacturerModel> ManufacturerModels { get; set; } = new List<ManufacturerModel>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual PromotionalSlider PromotionalSlider { get; set; }

    public virtual Social Social { get; set; }

    public virtual Type Type { get; set; }

    public virtual ICollection<Type> Types { get; set; } = new List<Type>();
}