// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Order : IAggregateRoot
{
    public int Id { get; set; }

    public int? CustomerId { get; set; }

    public bool? OrderStatus { get; set; }

    public int? ShopId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? CouponsId { get; set; }

    public int? StatusId { get; set; }

    public string PaymentStatus { get; set; }

    public int? OrderNumber { get; set; }

    public virtual ICollection<BillingAddress> BillingAddresses { get; set; } = new List<BillingAddress>();

    public virtual ICollection<Billing> Billings { get; set; } = new List<Billing>();

    public virtual AspNetUser Customer { get; set; }

    public virtual ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    public virtual ICollection<ShippingAddress> ShippingAddresses { get; set; } = new List<ShippingAddress>();

    public virtual ICollection<Shipping> Shippings { get; set; } = new List<Shipping>();

    public virtual Shop Shop { get; set; }

    public virtual Status Status { get; set; }

    public virtual ICollection<VendorOrderRelation> VendorOrderRelations { get; set; } = new List<VendorOrderRelation>();
}