// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class OrderLine : IAggregateRoot
{
    public int Id { get; set; }

    public int? ProductId { get; set; }

    public int? OrderId { get; set; }

    public int? Quantity { get; set; }

    public decimal? Amount { get; set; }

    public decimal? SalesTax { get; set; }

    public decimal? Total { get; set; }

    public decimal? PaidTotal { get; set; }

    public decimal? Discount { get; set; }

    public decimal? DeliveryFee { get; set; }

    public string DeliveryTime { get; set; }

    public string Language { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }
}