// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class PaymentHistory : IAggregateRoot
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string VendorId { get; set; }

    public string PaymentId { get; set; }

    public string Status { get; set; }

    public decimal? ChargedAmount { get; set; }

    public int? OrderId { get; set; }
}