// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class ProductTag : IAggregateRoot
{
    public int Id { get; set; }

    public int? ProductId { get; set; }

    public int? TagId { get; set; }

    public virtual Product Product { get; set; }

    public virtual Tag Tag { get; set; }
}