// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Profile : IAggregateRoot
{
    public int Id { get; set; }

    public string Avatar { get; set; }

    public string Bio { get; set; }

    public string Contact { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? CustomerId { get; set; }

    public string Socials { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? ImageId { get; set; }

    public int? SocialId { get; set; }

    public int? ProductId { get; set; }

    public virtual AspNetUser Customer { get; set; }

    public virtual Image Image { get; set; }

    public virtual Product Product { get; set; }

    public virtual Social Social { get; set; }
}