// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class PromotionalSlider : IAggregateRoot
{
    public int Id { get; set; }

    public int? TypeId { get; set; }

    public string OriginalUrl { get; set; }

    public string ThumbnailUrl { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Manufacture> Manufactures { get; set; } = new List<Manufacture>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual Type Type { get; set; }
}