// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Rating : IAggregateRoot
{
    public int ProductId { get; set; }

    public int Rating1 { get; set; }

    public int? Total { get; set; }

    public int? PositiveFeedbacksCount { get; set; }

    public int? NegativeFeedbacksCount { get; set; }

    public string MyFeedback { get; set; }

    public int? AbusiveReportsCount { get; set; }

    public int? OrderId { get; set; }

    public string Comments { get; set; }

    public int Id { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }
}