// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Setting : IAggregateRoot
{
    public int ShopId { get; set; }

    public string Contact { get; set; }

    public string Website { get; set; }

    public decimal? LocationLat { get; set; }

    public decimal? LocationLng { get; set; }

    public string LocationCity { get; set; }

    public string LocationState { get; set; }

    public string LocationCountry { get; set; }

    public string LocationFormattedAddress { get; set; }

    public string LocationZip { get; set; }

    public int? ProductId { get; set; }

    public virtual Product Product { get; set; }

    public virtual Shop Shop { get; set; }
}