// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Shipping : IAggregateRoot
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public string TrackingNo { get; set; }

    public int? Amount { get; set; }

    public string Type { get; set; }

    public bool? Global { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    public virtual Order Order { get; set; }

    public virtual ICollection<ShippingAddress> ShippingAddresses { get; set; } = new List<ShippingAddress>();
}