// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Shop : IAggregateRoot
{
    public int Id { get; set; }

    public int? OwnerId { get; set; }

    public string Name { get; set; }

    public string Slug { get; set; }

    public string Description { get; set; }

    public int? CoverImageId { get; set; }

    public int? LogoImageId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsActive { get; set; }

    public string CertificateUrl { get; set; }

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    public virtual ICollection<Attribute> Attributes { get; set; } = new List<Attribute>();

    public virtual ICollection<Author> Authors { get; set; } = new List<Author>();

    public virtual Balance Balance { get; set; }

    public virtual ICollection<Coupon> Coupons { get; set; } = new List<Coupon>();

    public virtual Image CoverImage { get; set; }

    public virtual Image LogoImage { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    public virtual Setting Setting { get; set; }

    public virtual ICollection<ShopSocial> ShopSocials { get; set; } = new List<ShopSocial>();

    public virtual ICollection<Social> Socials { get; set; } = new List<Social>();

    public virtual ICollection<Svcrelation> Svcrelations { get; set; } = new List<Svcrelation>();
}