// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Social : IAggregateRoot
{
    public int Id { get; set; }

    public int? ShopId { get; set; }

    public string Url { get; set; }

    public string Icon { get; set; }

    public string Type { get; set; }

    public string Link { get; set; }

    public int? ProductId { get; set; }

    public virtual ICollection<Manufacture> Manufactures { get; set; } = new List<Manufacture>();

    public virtual Product Product { get; set; }

    public virtual ICollection<Profile> Profiles { get; set; } = new List<Profile>();

    public virtual Shop Shop { get; set; }

    public virtual ICollection<ShopSocial> ShopSocials { get; set; } = new List<ShopSocial>();
}