// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Svcrelation : IAggregateRoot
{
    public int Id { get; set; }

    public decimal? Price { get; set; }

    public string Size { get; set; }

    public int? ShopId { get; set; }

    public virtual Shop Shop { get; set; }
}