// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Tag : IAggregateRoot
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Language { get; set; }

    public List<string> TranslatedLanguages { get; set; }

    public string Slug { get; set; }

    public string Details { get; set; }

    public string Icon { get; set; }

    public int? TypeId { get; set; }

    public int? ImageId { get; set; }

    public virtual Image Image { get; set; }

    public virtual ICollection<ProductTag> ProductTags { get; set; } = new List<ProductTag>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual Type Type { get; set; }
}