// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Tax : IAggregateRoot
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal? Rate { get; set; }

    public bool? IsGlobal { get; set; }

    public string Country { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public string City { get; set; }

    public string Priority { get; set; }

    public bool? OnShipping { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}