// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class Type : IAggregateRoot
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Slug { get; set; }

    public string Logo { get; set; }

    public int? ProductId { get; set; }

    public virtual ICollection<Banner> Banners { get; set; } = new List<Banner>();

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

    public virtual ICollection<Manufacture> Manufactures { get; set; } = new List<Manufacture>();

    public virtual Product Product { get; set; }

    public virtual ICollection<PromotionalSlider> PromotionalSliders { get; set; } = new List<PromotionalSlider>();

    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();

    public virtual ICollection<Manufacture> Manufacturers { get; set; } = new List<Manufacture>();
}