// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Autopart.Domain.SharedKernel;

namespace Autopart.Domain.Models;

public partial class VendorOrderRelation : IAggregateRoot
{
    public int Id { get; set; }

    public int? VendorId { get; set; }

    public int? OrderId { get; set; }

    public virtual Order Order { get; set; }

    public virtual AspNetUser Vendor { get; set; }
}